// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Stable responses for HTTP limit violations.

use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::response::Response;

/// A stable, request-independent rejection generated by the infrastructure.
///
/// # Examples
///
/// ```
/// use qubit_web::WebRejection;
///
/// let rejection = WebRejection::BodyTooLarge;
/// assert_eq!(rejection.status(), axum::http::StatusCode::PAYLOAD_TOO_LARGE);
/// assert_eq!(rejection.code(), "body_too_large");
/// ```
#[must_use]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WebRejection {
    /// The declared or streamed request body exceeded its byte budget.
    BodyTooLarge,
    /// No short-request capacity was available.
    CapacityExceeded,
    /// An ordinary short request exceeded its processing deadline.
    RequestTimedOut,
}

impl WebRejection {
    /// Returns the stable HTTP status for this rejection.
    ///
    /// # Returns
    ///
    /// The status to use in the corresponding problem response.
    #[must_use]
    #[inline]
    pub const fn status(self) -> StatusCode {
        match self {
            Self::BodyTooLarge => StatusCode::PAYLOAD_TOO_LARGE,
            Self::CapacityExceeded => StatusCode::SERVICE_UNAVAILABLE,
            Self::RequestTimedOut => StatusCode::GATEWAY_TIMEOUT,
        }
    }

    /// Returns the stable machine-readable code.
    ///
    /// # Returns
    ///
    /// A stable code that does not include request data.
    #[must_use]
    #[inline]
    pub const fn code(self) -> &'static str {
        match self {
            Self::BodyTooLarge => "body_too_large",
            Self::CapacityExceeded => "capacity_exceeded",
            Self::RequestTimedOut => "request_timeout",
        }
    }
}

impl IntoResponse for WebRejection {
    /// Converts the rejection into its safe problem response.
    ///
    /// # Returns
    ///
    /// An HTTP response with the stable status and machine-readable code.
    fn into_response(self) -> Response {
        let title = match self {
            Self::BodyTooLarge => "Payload Too Large",
            Self::CapacityExceeded => "Service Unavailable",
            Self::RequestTimedOut => "Gateway Timeout",
        };
        let payload = format!(
            "{{\"type\":\"about:blank\",\"title\":\"{title}\",\"status\":{},\"code\":\"{}\"}}",
            self.status().as_u16(),
            self.code()
        );
        (
            self.status(),
            [(axum::http::header::CONTENT_TYPE, "application/problem+json")],
            payload,
        )
            .into_response()
    }
}
