[package]
name = "qubit-web-macros"
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
license = "Apache-2.0"
description = "Procedural macros for qubit-web"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
axum = "0.8"
qubit-web = { version = "0.2.0", path = ".." }
