// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
use std::collections::HashMap;
use std::collections::HashSet;
use std::sync::Arc;

use axum::Router;

use super::ControllerDefinition;
use super::ControllerRouteError;
use crate::limit::HttpLimits;
use crate::limit::LimitState;

/// Builds an Axum router from explicitly supplied Controller instances.
///
/// # Type Parameters
///
/// * `S` - Cloneable, thread-safe application state required by the router.
///
/// # Examples
///
/// An empty router can be assembled without declaring any controllers:
///
/// ```
/// use qubit_web::mvc::ControllerRoutes;
///
/// let router = ControllerRoutes::<()>::new().finish();
/// let _ = router;
/// ```
#[must_use]
pub struct ControllerRoutes<S = ()> {
    /// Axum router accumulated during assembly.
    router: Router<S>,
    /// Methods already declared for each complete route template.
    declared: HashMap<&'static str, HashSet<&'static str>>,
    /// Shared limits passed to each registered controller.
    limit_state: LimitState,
}

impl<S> Default for ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    /// Creates an empty Controller router. Short routes added to it use
    /// `HttpLimits::default()` (1 MiB body, 256 concurrent requests, and a
    /// 30-second timeout) until `with_http_limits` supplies a replacement
    /// policy.
    ///
    /// # Examples
    ///
    /// ```
    /// use qubit_web::mvc::ControllerRoutes;
    ///
    /// let router = ControllerRoutes::<()>::new().finish();
    /// let _ = router;
    /// ```
    pub fn new() -> Self {
        Self {
            router: Router::new(),
            declared: HashMap::new(),
            limit_state: LimitState::new(HttpLimits::default()),
        }
    }

    /// Replaces the default finite limits for all short routes added to this
    /// builder afterward.
    ///
    /// SSE and WebSocket routes keep the same diagnostics but skip the
    /// short-request body, concurrency, and deadline limits. Configure this
    /// before adding Controllers so their routes share one concurrency limit.
    ///
    /// # Parameters
    ///
    /// * `http_limits` - Replacement policy shared by short routes added
    ///   afterward.
    ///
    /// # Returns
    ///
    /// The same builder with the replacement policy installed.
    pub fn with_http_limits(mut self, http_limits: HttpLimits) -> Self {
        self.limit_state = LimitState::new(http_limits);
        self
    }

    /// Adds all routes declared by one Controller instance.
    ///
    /// # Parameters
    ///
    /// * `controller` - Shared controller instance used by registered handlers.
    ///
    /// # Type Parameters
    ///
    /// * `C` - Controller type generated by the controller attribute macro.
    ///
    /// # Returns
    ///
    /// The updated builder after every route declaration passes preflight.
    ///
    /// # Errors
    ///
    /// Returns [`ControllerRouteError::DuplicateMethod`] for an exact duplicate
    /// method and path, [`ControllerRouteError::PatternConflict`] for distinct
    /// templates that match the same paths, or
    /// [`ControllerRouteError::InvalidPath`] for an invalid route template.
    /// No routes are registered unless every declaration passes preflight.
    #[allow(clippy::should_implement_trait)]
    pub fn add<C>(mut self, controller: Arc<C>) -> Result<Self, ControllerRouteError>
    where
        C: ControllerDefinition<S>,
    {
        let mut declared = self.declared.clone();
        let mut matcher = matchit::Router::<()>::new();
        for path in self.declared.keys() {
            matcher
                .insert(*path, ())
                .map_err(|error| ControllerRouteError::InvalidPath {
                    path,
                    reason: error.to_string(),
                })?;
        }
        for route in C::route_metadata() {
            if declared
                .get(route.path())
                .is_some_and(|methods| methods.contains(route.method()))
            {
                return Err(ControllerRouteError::DuplicateMethod {
                    method: route.method(),
                    path: route.path(),
                });
            }
            if !declared.contains_key(route.path())
                && let Err(error) = matcher.insert(route.path(), ())
            {
                return match error {
                    matchit::InsertError::Conflict { with } => Err(ControllerRouteError::PatternConflict {
                        path: route.path(),
                        existing_path: with,
                    }),
                    error => Err(ControllerRouteError::InvalidPath {
                        path: route.path(),
                        reason: error.to_string(),
                    }),
                };
            }
            declared.entry(route.path()).or_default().insert(route.method());
        }
        self.router = C::register(controller, self.router, self.limit_state.clone());
        self.declared = declared;
        Ok(self)
    }

    /// Finishes assembly and returns the Axum router.
    ///
    /// # Returns
    ///
    /// The assembled router.
    pub fn finish(self) -> Router<S> {
        self.router
    }
}
