// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
use std::collections::HashSet;
use std::sync::Arc;

use axum::Router;

use super::ControllerDefinition;
use super::ControllerRouteConflict;
use crate::limit::HttpLimits;
use crate::limit::LimitState;

/// Builds an Axum router from explicitly supplied Controller instances.
///
/// # Type Parameters
///
/// * `S` - Cloneable, thread-safe application state required by the router.
///
/// # Examples
///
/// An empty router can be assembled without declaring any controllers:
///
/// ```
/// use qubit_web::mvc::ControllerRoutes;
///
/// let router = ControllerRoutes::<()>::new().finish().unwrap();
/// let _ = router;
/// ```
#[must_use]
pub struct ControllerRoutes<S = ()> {
    /// Axum router accumulated during assembly.
    router: Router<S>,
    /// Method/template pairs already declared by added controllers.
    declared: HashSet<(&'static str, &'static str)>,
    /// Shared limits passed to each registered controller.
    limit_state: LimitState,
}

impl<S> Default for ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    /// Creates an empty Controller router.
    ///
    /// # Examples
    ///
    /// ```
    /// use qubit_web::mvc::ControllerRoutes;
    ///
    /// let router = ControllerRoutes::<()>::new().finish().unwrap();
    /// let _ = router;
    /// ```
    pub fn new() -> Self {
        Self {
            router: Router::new(),
            declared: HashSet::new(),
            limit_state: LimitState::new(HttpLimits::default()),
        }
    }

    /// Sets the finite limits applied to all short routes added to this
    /// builder.
    ///
    /// SSE and WebSocket routes keep the same diagnostics but skip the
    /// short-request body, concurrency, and deadline limits. Configure this
    /// before adding Controllers so their routes share one concurrency limit.
    ///
    /// # Parameters
    ///
    /// * `http_limits` - Policy shared by short routes added afterward.
    ///
    /// # Returns
    ///
    /// The same builder with the supplied policy installed.
    pub fn with_http_limits(mut self, http_limits: HttpLimits) -> Self {
        self.limit_state = LimitState::new(http_limits);
        self
    }

    /// Adds all routes declared by one Controller instance.
    ///
    /// # Parameters
    ///
    /// * `controller` - Shared controller instance used by registered handlers.
    ///
    /// # Type Parameters
    ///
    /// * `C` - Controller type generated by the controller attribute macro.
    ///
    /// # Returns
    ///
    /// The updated builder, or a conflict identifying the duplicate method and
    /// path.
    ///
    /// # Errors
    ///
    /// Returns [`ControllerRouteConflict`] when the controller duplicates a
    /// method/template pair already declared by this builder.
    #[allow(clippy::should_implement_trait)]
    pub fn add<C>(mut self, controller: Arc<C>) -> Result<Self, ControllerRouteConflict>
    where
        C: ControllerDefinition<S>,
    {
        for route in C::route_metadata() {
            if self.declared.contains(&(route.method(), route.path())) {
                return Err(ControllerRouteConflict::new(route.method(), route.path()));
            }
        }
        self.declared
            .extend(C::route_metadata().iter().map(|route| (route.method(), route.path())));
        self.router = C::register(controller, self.router, self.limit_state.clone());
        Ok(self)
    }

    /// Finishes assembly and returns the Axum router.
    ///
    /// # Returns
    ///
    /// The assembled router, currently returned in `Ok` because all route
    /// conflicts are detected while adding controllers.
    ///
    /// # Errors
    ///
    /// This implementation does not currently return an error.
    pub fn finish(self) -> Result<Router<S>, ControllerRouteConflict> {
        Ok(self.router)
    }
}
