// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Explicit assembly for routes generated by Controller attributes.

use std::collections::HashSet;
use std::fmt;
use std::sync::Arc;

use axum::Router;

use crate::RouteKind;
use crate::limit::HttpLimits;
use crate::limit::LimitState;

/// One statically declared route produced by a Controller implementation.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct RouteMetadata {
    method: &'static str,
    path: &'static str,
    kind: RouteKind,
}

impl RouteMetadata {
    /// Creates route metadata for generated Controller code.
    pub const fn new(method: &'static str, path: &'static str, kind: RouteKind) -> Self {
        Self { method, path, kind }
    }

    /// Returns the HTTP method name.
    pub const fn method(&self) -> &'static str {
        self.method
    }

    /// Returns the normalized route template.
    pub const fn path(&self) -> &'static str {
        self.path
    }

    /// Returns the route's long-lived or short-request classification.
    pub const fn kind(&self) -> RouteKind {
        self.kind
    }
}

/// Internal contract implemented by `#[rest_controller]` expansions.
#[doc(hidden)]
pub trait ControllerDefinition<S>: Send + Sync + 'static
where
    S: Clone + Send + Sync + 'static,
{
    /// Static metadata used to reject conflicts before inserting routes.
    fn route_metadata() -> &'static [RouteMetadata];

    /// Adds all routes for one explicitly supplied Controller instance.
    fn register(self: Arc<Self>, router: Router<S>, limit_state: LimitState) -> Router<S>;
}

/// Error returned when two Controllers declare the same method and template.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ControllerRouteConflict {
    method: &'static str,
    path: &'static str,
}

impl ControllerRouteConflict {
    /// Returns the duplicated method.
    pub const fn method(&self) -> &'static str {
        self.method
    }

    /// Returns the duplicated route template.
    pub const fn path(&self) -> &'static str {
        self.path
    }
}

impl fmt::Display for ControllerRouteConflict {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "duplicate Controller route: {} {}", self.method, self.path)
    }
}

impl std::error::Error for ControllerRouteConflict {}

/// Builds an Axum router from explicitly supplied Controller instances.
pub struct ControllerRoutes<S = ()> {
    router: Router<S>,
    declared: HashSet<(&'static str, &'static str)>,
    limit_state: LimitState,
}

impl<S> Default for ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> ControllerRoutes<S>
where
    S: Clone + Send + Sync + 'static,
{
    /// Creates an empty Controller router.
    pub fn new() -> Self {
        Self {
            router: Router::new(),
            declared: HashSet::new(),
            limit_state: LimitState::new(HttpLimits::default()),
        }
    }

    /// Sets the finite limits applied to all short routes added to this
    /// builder.
    ///
    /// SSE and WebSocket routes keep the same diagnostics but skip the
    /// short-request body, concurrency, and deadline limits. Configure this
    /// before adding Controllers so their routes share one concurrency limit.
    pub fn with_http_limits(mut self, http_limits: HttpLimits) -> Self {
        self.limit_state = LimitState::new(http_limits);
        self
    }

    /// Adds all routes declared by one Controller instance.
    #[allow(clippy::should_implement_trait)]
    pub fn add<C>(mut self, controller: Arc<C>) -> Result<Self, ControllerRouteConflict>
    where
        C: ControllerDefinition<S>,
    {
        for route in C::route_metadata() {
            if self.declared.contains(&(route.method, route.path)) {
                return Err(ControllerRouteConflict {
                    method: route.method,
                    path: route.path,
                });
            }
        }
        self.declared
            .extend(C::route_metadata().iter().map(|route| (route.method, route.path)));
        self.router = C::register(controller, self.router, self.limit_state.clone());
        Ok(self)
    }

    /// Finishes assembly and returns the Axum router.
    pub fn finish(self) -> Result<Router<S>, ControllerRouteConflict> {
        Ok(self.router)
    }
}

/// Joins a Controller prefix and child template with exactly one separator.
pub fn join_route_path(prefix: &str, child: &str) -> String {
    if prefix == "/" {
        if child.is_empty() {
            "/".to_owned()
        } else {
            child.trim_start_matches('/').to_owned().insert_slash()
        }
    } else if child.is_empty() {
        prefix.to_owned()
    } else {
        format!(
            "{}{}",
            prefix.trim_end_matches('/'),
            if child.starts_with('/') {
                child.to_owned()
            } else {
                format!("/{child}")
            }
        )
    }
}

trait InsertSlash {
    fn insert_slash(self) -> String;
}

impl InsertSlash for String {
    fn insert_slash(self) -> String {
        if self.starts_with('/') {
            self
        } else {
            format!("/{self}")
        }
    }
}
