// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Explicit assembly for routes generated by Controller attributes.

mod controller_definition;
mod controller_route_conflict;
mod controller_routes;
mod join_route_path;
mod route_metadata;
mod internal {
    mod insert_slash;

    pub(super) use insert_slash::InsertSlash;
}

pub use controller_definition::ControllerDefinition;
pub use controller_route_conflict::ControllerRouteConflict;
pub use controller_routes::ControllerRoutes;
pub use join_route_path::join_route_path;
pub use route_metadata::RouteMetadata;
